import "./styles/globals.css";
import type { Metadata } from "next";
import StyledComponentsRegistry from "@/app/components/Provider/AntdRegistry";
import ReactQueryProvider from "@/app/components/Provider/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
